"""
Model training script for ApexInvest Advisor.

This module reads the processed feature table generated by the
ingestion pipeline, constructs a target variable (next‑day price
movement), trains a machine learning classifier and saves the
resulting model to disk.  The scikit‑learn library is used because
it is free and open source【615955049487310†L510-L518】 and offers a wide range of
algorithms and utilities【615955049487310†L543-L551】.  The default model is a
RandomForestClassifier, but you can experiment with other models
provided by scikit‑learn.
"""

import joblib
import os
from typing import Tuple

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score


DATA_PATH = "data_ingestion/dataset.csv"
MODEL_PATH = "ml_model/model.pkl"


def load_dataset(path: str = DATA_PATH) -> pd.DataFrame:
    """Load the feature table from a CSV file and compute the target.

    The target variable is defined as the direction of the next day's
    closing price relative to the current day.  A positive movement
    results in label 1 ("Buy"), a negative movement results in label
    0 ("Sell").  Rows without a next day (e.g. the last day for each
    ticker) are dropped.
    """

    df = pd.read_csv(path, parse_dates=["date"])
    # sort by ticker and date
    df.sort_values(["ticker", "date"], inplace=True)
    # compute next day return per ticker
    df["next_close"] = df.groupby("ticker")["Close"].shift(-1)
    df["target"] = (df["next_close"] > df["Close"]).astype(int)
    df.dropna(subset=["target"], inplace=True)
    return df


def prepare_features(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.Series]:
    """Extract feature columns and target vector.
    Drop columns that are not used for training (identifiers, target and labels).
    """

    feature_cols = ["returns", "SMA_14", "EMA_14", "RSI_14", "sentiment"]
    X = df[feature_cols].astype(float)
    y = df["target"].astype(int)
    # replace infinities and NaNs with zero
    X.replace([np.inf, -np.inf], np.nan, inplace=True)
    X.fillna(0, inplace=True)
    return X, y


def train_model(X: pd.DataFrame, y: pd.Series) -> RandomForestClassifier:
    """Train a random forest classifier on the provided features.

    Splits the data into training and testing sets, fits the model
    and prints evaluation metrics.  Returns the fitted model.
    """

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=None,
        n_jobs=-1,
        random_state=42,
    )
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Model accuracy:", acc)
    print(classification_report(y_test, y_pred))
    return model


def main() -> None:
    """Main entry point for training the model."""

    if not os.path.exists(DATA_PATH):
        raise FileNotFoundError(
            f"Dataset not found at {DATA_PATH}. Run the ingestion pipeline first."
        )
    df = load_dataset(DATA_PATH)
    X, y = prepare_features(df)
    model = train_model(X, y)
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    joblib.dump(model, MODEL_PATH)
    print(f"Saved trained model to {MODEL_PATH}")


if __name__ == "__main__":
    main()